.TH "ccc" "7" "0.5.1" "Pozsar Zsolt" "Colour code decoder"
.SH "NAME"
.LP 
CCC \- colour code decoder
.SH "SYNTAX"
.LP
ccc
.br 
.SH "DESCRIPTION"
.LP 
    It is an colour code decoder for electronic components. It useable
on Linux and Windows.
.br
Categories:
.br
    1. resistors
.br
     - 3 band colour code
.br
     - 4 band colour code
.br
     - 5 band colour code
.br
     - 6 band colour code
.br
    2. capacitors
.br
     - 3 band colour code (ceramic)
.br
     - 5 band colour code (ceramic)
.br
     - 5 band colour code
.br
     - 4 band colour code (tantalum capacitors)
.br
     - numeric code
.br
    3. 1Nxxxx diodes
.br
     - 3 band colour code
.br
     - 4 band colour code
.br
     - 5 band colour code
.br
    4. inductors
.br
     - 4 band colour code
.SH "ENVIRONMENTAL VARIABLES"
.LP 
\fBLANG\fP
.br
You can set language of labels with these variables. If it is a
non-supported language, text will be English. Format: en, en_US.
Available languages are English, German and Hungarian.
.SH "AUTHOR"
.LP 
Pozsar Zsolt
.br
Homepage: http://www.pozsarzs.hu
.br
E-mail and MSN:   pozsarzs@gmail.com
.br
