.TH "ccc" "7" "0.5" "Pozsar Zsolt" "Színkód dekóder"
.SH "NÉV"
.LP 
CCC \- színkód dekóder
.SH "ÁTTEKINTÉS"
.LP
ccc
.br 
.SH "LEÍRÁS"
.LP 
    Ez a program szín- és számjelölésű elektronikai alkatrészek
azonosításához nyújt segítséget. Használható Linux és Windows operációs
rendszereken.
.br
Kategóriák:
.br
    1. ellenállások
.br
     - 3 sávos színkód
.br
     - 4 sávos színkód
.br
     - 5 sávos színkód
.br
     - 6 sávos színkód
.br
    2. kondenzátorok
.br
     - 3 sávos színkód (kerámia)
.br
     - 5 sávos színkód (kerámia)
.br
     - 5 pontos színkód
.br
     - 4 sávos színkód (tantál kondenzátorok)
.br
     - számkód
.br
    3. 1Nxxxx diódák
.br
     - 3 sávos színkód
.br
     - 4 sávos színkód
.br
     - 5 sávos színkód
.br
    4. tekercsek
.br
     - 4 sávos színkód
.SH "KÖRNYEZETI VÁLTOZÓK"
.LP 
\fBLANG\fP
.br
Használd a 'LANG' környezeti változót program nyelvének beállításához.
Ha ez egy nem támogatott nyelv, akkor a feliratok angol nyelvűek lesznek.
Támogatott nyelvek: angol és magyar.
.SH "SZERZŐ"
.LP 
Pozsár Zsolt
.br
Honlap: http://www.pozsarzs.hu
.br
E-mail:   pozsarzs@t-email.hu
.br
MSN:      pozsarzs@t-email.hu
.br
